### PR TITLE
Commented out debugging std::cout

### PR DESCRIPTION
**Pull request by vpicaver**

### CODE REVIEW

**Comment by jedwards1211** [comment]
Do you know if there's any way to get a stack trace with Catch?  Or way to get some info about which case failed without repeating a bunch of code?

**Comment by vpicaver** [comment]
I know there's an INFO(), which prints out with the last failed test. I
don't know if can stack trace in catch.

**Comment by jedwards1211** [comment]
Oh, INFO is perfect.  I'll use that, thanks!

**Comment by vpicaver** [comment]
Cool! :)

On Thursday, January 7, 2016, Andy Edwards <notifications@github.com> wrote:

> Oh, INFO is perfect. I'll use that, thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jedwards1211/dewalls/pull/7#issuecomment-169698539>.
>


-- 
Phi|ip

Sent from Gmail Mobile

**Comment by jedwards1211** [comment]
Okay, I replaced those with INFO.

**Pull request closed without merging**
