### PR TITLE
Fixes to multiple build related issues and memory leak fix

### PR DESCRIPTION
**Pull request by vpicaver**

### CODE REVIEW

**Comment by jedwards1211** [comment]
Cool, let me add you as an owner, since only Cavewhere is using this right now and you know more about Qt proj maintenance than I do

**Comment by jedwards1211** [comment]
Thinking back there are multiple issues I've fixed in my Java walls parser that I need to Port to this one soon
Eventually I want to write a JS walls parser with a cleaner, simpler architecture...it would be possible to call that in-process with Qt right?

**Comment by vpicaver** [comment]
Yea, it supports JS, specifically pure ECMAScript. It would be really cool if we could share code bases. Here are the scripting options: https://doc.qt.io/qt-5/topics-scripting.html. Here's the engine documentation: https://doc.qt.io/qt-5/qjsengine.html

**Comment by jedwards1211** [comment]
Cool, yeah I've started building various JS cave data infrastructure here: https://github.com/speleotica
(in TypeScript technically, but compiles to pure ECMAScript)

**Comment by vpicaver** [comment]
Cool! I'll have to check it out.

**Pull request merged**
