### PR TITLE
Fixed Qt String compiling issues for 5.5 on OS X

### PR DESCRIPTION
**Pull request by vpicaver**

### CODE REVIEW

**Comment by jedwards1211** [comment]
If everything goes right I'll be buying a MacBook tonight to replace my old comp :)  Then we wouldn't have these kinds of problems in the future

**Comment by vpicaver** [comment]
I'm currently fighting qbs on a couple of issue right now on linux... It's
a bit annoying.

Phi|ip

**Comment by jlillest** [comment]
I've got some similar issues with qbs to make the linux build, let me know if I can help.

**Comment by vpicaver** [comment]
I think there's a bug in qbs, that I'm going to try to report.

**Pull request merged**
