### PR TITLE
Fixed OS X Clang Compiling errors

### PR DESCRIPTION
**Pull request by vpicaver**
- Added error or Warnings for Mac and Linux
- Fixed compiling errors
- Tests passed on Mac

### CODE REVIEW

**Comment by jlillest** [comment]
The above change fixed my C++11 errors, but now I'm getting compiler errors with system/QT libraries:

```
compiling wallsparser.cpp
compiling wallsvisitor.cpp
compiling wallstypes.cpp
compiling wallsunits.cpp
/usr/bin/clang++-3.5 -m64 -g -Wall -Wextra -pipe -x c++ -stdlib=libc++ -std=c++11 -Werror -fPIC -DQT_CORE_LIB -I/home/jlillestolen/cavecode/cavewhere/dewalls/src -I/usr/local/bin/Qt5.3.1/5.3/gcc_64/include -I/usr/local/bin/Qt5.3.1/5.3/gcc_64/include/QtCore -I/usr/local/bin/Qt5.3.1/5.3/gcc_64/mkspecs/linux-g++ -I/home/jlillestolen/cavecode/cavewhere-build/qtc_Desktop-debug/dewalls.qtc_Desktop/GeneratedFiles -c /home/jlillestolen/cavecode/cavewhere/dewalls/src/wallstypes.cpp -o /home/jlillestolen/cavecode/cavewhere-build/qtc_Desktop-debug/dewalls.qtc_Desktop/.obj/src/wallstypes.cpp.o
In file included from /home/jlillestolen/cavecode/cavewhere/dewalls/src/wallstypes.cpp:1:
In file included from /home/jlillestolen/cavecode/cavewhere/dewalls/src/wallstypes.h:4:
In file included from /usr/local/bin/Qt5.3.1/5.3/gcc_64/include/QtCore/QString:1:
In file included from /usr/local/bin/Qt5.3.1/5.3/gcc_64/include/QtCore/qstring.h:45:
In file included from /usr/local/bin/Qt5.3.1/5.3/gcc_64/include/QtCore/qchar.h:45:
In file included from /usr/local/bin/Qt5.3.1/5.3/gcc_64/include/QtCore/qglobal.h:74:
/usr/local/bin/Qt5.3.1/5.3/gcc_64/include/QtCore/qcompilerdetection.h:845:11: fatal error: 'utility' file not found
# include <utility>
          ^
1 error generated.
Process failed with exit code 1.
```

What version of Qt are you using?  Am I missing some plugin or additional Qt package?

**Comment by jlillest** [comment]
Ok, it seems to be the C++ system library <utility> (http://www.cplusplus.com/reference/utility/).  Now I just need to find which package provides it on debian/ubuntu.

**Comment by jlillest** [comment]
I updated libc++-dev and that seemed to install the missing header file.

Now I'm getting a huge amount of errors when linking both dewalls and protoc.  Signs are pointing towards my system install.

**Comment by jedwards1211** [comment]
Compiled and tested on my windows machine.  Thanks guys!  Sorry it took so long!  Once I lost the notification, I forgot that there were PRs here as opposed to my fork of Cavewhere or the main project.

**Comment by vpicaver** [comment]
I too get lost in github's fork land...

**Pull request merged**
